#define Y2_GPIO_NUM       47
#define Y3_GPIO_NUM       38
#define Y4_GPIO_NUM       39
#define Y5_GPIO_NUM       48
#define Y6_GPIO_NUM       21
#define Y7_GPIO_NUM       13
#define Y8_GPIO_NUM       12
#define Y9_GPIO_NUM       10
#define XCLK_GPIO_NUM      11
#define PCLK_GPIO_NUM     14
#define VSYNC_GPIO_NUM    8
#define HREF_GPIO_NUM     9
#define SIOD_GPIO_NUM     17
#define SIOC_GPIO_NUM     18
#define PWDN_GPIO_NUM     -1
#define RESET_GPIO_NUM    -1
